version: '3.8'

services:
  news_scrapper:
    image: news_scrapper:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/usr/src/app
    command: ["streamlit", "run", "--server.enableCORS", "false", "--server.port", "8501", "main_page.py"]
